import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { UniversalService } from 'src/app/services/universal.service';

@Component({
  selector: 'app-staff-pay-roll',
  templateUrl: './staff-pay-roll.component.html',
  styleUrls: ['./staff-pay-roll.component.scss']
})
export class StaffPayRollComponent {
  public staffDetail: boolean = false;
  constructor(private router: Router, private cd: ChangeDetectorRef) {}
  public PayrollTable: any = [
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      name: 'Jhon Smith',
      joining: '12-Oct-2023',
      salary: '10000',
      allownces: '5000',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
  ];
  public Waitertables: any = [
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Tuesday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Ending',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Wednesday',
      checkin: '-',
      checkout: '-',
      availability: 'Present',
      status: 'Ending',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'thursday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'friday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Saturday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Sunday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Tuesday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Wednesday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'thursday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'friday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Saurday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Sunday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Ending',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Ending',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Ending',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Ending',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Ending',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Ending',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'Complete',
      waiter: 'Lawrence',
      payment: 'Cash',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
    {
      date: '01-sep-2022',
      day: 'Monday',
      checkin: '9:00AM',
      checkout: '6:00PM',
      availability: 'Present',
      status: 'In process',
      waiter: 'Lawrence',
      payment: 'Card',
      action: { process: 'process', edit: 'edit', cancel: 'cancel' },
    },
  ];
  ngOnInit(): void {
    this.observe('staffpayroll');
  }
  async observe(path: string) {
    // if (path) {
    //   this.router.navigate([`master/${path}`]);
    // }
    // UniversalService.routePath.subscribe((res: string) => {
    //   let path = res.toLowerCase();
    //   this.router.navigate([`master/${path}`]);
    //   this.cd.detectChanges();
    // });
    UniversalService.StaffDetailView.subscribe((res: boolean) => {
      this.staffDetail = res;
      this.cd.detectChanges();
    });
  }
}
